name: homebridge
version: '2'
services:
  homebridge:
    # had to use homebridge/homebridge:latest because there are no versions listed
    image: homebridge/homebridge:latest@sha256:8113f6a0c04e4d25ae07fe59a418b692507c14a12bb2bdceefc85d46a734420c
    restart: always
    network_mode: host
    volumes:
      - /DATA/AppData/$AppID/config:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
x-casaos:
  id: org.icewhale.homebridge
  main: homebridge
  icon: https://cdn.jsdelivr.net/gh/Dengwii/Casaos-asv2@gh-pages/apps/org.icewhale.homebridge/assets/icon.svg
  title:
    en_US: Homebridge
  index: /
  port_map: "8581"
  version: "2.1.0"
